name: MyWF01
on:
  workflow_dispatch:
env:
  WF-ENV: '01-WF-ENV'
jobs:  
  myjob01:  
    name: My Job One
    runs-on: ubuntu-latest
    env:
      jbs-env: '02-JBS-ENV'
    steps:
      - name: My Step 01 from job01
        id: job01step01        
        run: echo "this is step02 from job01, WF-ENV - ${{ env.WF-ENV }}, jbs-env - ${{ env.jbs-env}}, stp-env - ${{ env.stp-env}}, rs01 - ${{ secrets.rs01 }}"
        env: 
          stp-env: '03-STP-ENV'
      - name: My Step 02 from job01
        id: job01step02
        run: echo "this is step02 from job01. ${{ env.test}}"
      - name: My Step 03 from job01
        id: job01step03
        run: |
          echo "this is step03 from job01"
          echo ${{ github.actor }}
          echo ${{ env.WF-ENV }}
          echo ${{ env.jbs-env }}
          echo ${{ vars.REFVAR01 }}
          echo ${{ secrets.rs01 }}
  myjob02:
    name: My Job two
    runs-on: ubuntu-latest
    
    steps:
      - name: My Step 01 from job02
        id: job02step01
        run: echo "this is step01 from job02"
      - name: My Step 02 from job02
        id: job02step02
        run: echo "this is step02 from job02"
      - name: My Step 03 from job02
        id: job02step03
        run: echo "this is step03 from job02"
  myjob03:
    name: My Job three
    runs-on: ubuntu-latest
    
    steps:
      - name: My Step 01 from job03
        id: job03step01
        run: echo "this is step01 from job03"
      - name: My Step 02 from job03
        id: job03step02
        run: echo "this is step02 from job03"
      - name: My Step 03 from job03
        id: job03step03
        run: echo "this is step03 from job03"
